export const constants = {
  UPLOAD_PHOTOS: "UPLOAD_PHOTOS",
  UPLOAD_PHOTOS_START: "UPLOAD_PHOTOS_START",
  UPLOAD_PHOTOS_SUCCESS: "UPLOAD_PHOTOS_SUCCESS",
  UPLOAD_PHOTOS_FAILURE: "UPLOAD_PHOTOS_FAILURE",
  SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
  RESET_UPLOAD_DATA: "RESET_UPLOAD_DATA",
};
