export const constants = {
  UPLOAD_PHOTOS_START: "UPLOAD_PHOTOS_START",
  UPLOAD_PHOTOS_SUCCESS: "UPLOAD_PHOTOS_SUCCESS",
  UPLOAD_PHOTOS_FAILURE: "UPLOAD_PHOTOS_FAILURE",
  SET_OVERALL_SIZE: "SET_OVERALL_SIZE",
  SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
  RESET_UPLOAD_DATA: "RESET_UPLOAD_DATA",
};

export const API_URL = process.env.REACT_APP_API_URL;
